export type DemoRow = {
  id: number;
  status: string;
  name: string;
  age: number;
  active: boolean;
  featured: boolean;
  updatedAt: string;
  uploadedBy: string;
  priority: string;
  tags: string[];
  rating: number;
};

export const initialRows: DemoRow[] = [
  {
    id: 1,
    status: "Ready",
    name: "Alpha",
    age: 29,
    active: true,
    featured: false,
    updatedAt: "2026-02-19",
    uploadedBy: "Nitin Ranganath",
    priority: "high",
    tags: ["frontend"],
    rating: 4,
  },
  {
    id: 2,
    status: "In Review",
    name: "Beta",
    age: 34,
    active: false,
    featured: true,
    updatedAt: "2026-02-18",
    uploadedBy: "Unnati Bamania",
    priority: "medium",
    tags: ["backend", "api"],
    rating: 3,
  },
  {
    id: 3,
    status: "Draft",
    name: "Gamma",
    age: 25,
    active: true,
    featured: false,
    updatedAt: "2026-02-17",
    uploadedBy: "Unnati Bamania",
    priority: "low",
    tags: ["ops"],
    rating: 2,
  },
  {
    id: 4,
    status: "Ready",
    name: "Delta",
    age: 31,
    active: false,
    featured: false,
    updatedAt: "2026-02-16",
    uploadedBy: "Nitin Ranganath",
    priority: "high",
    tags: ["frontend", "api"],
    rating: 5,
  },
  {
    id: 5,
    status: "In Review",
    name: "Epsilon",
    age: 27,
    active: true,
    featured: false,
    updatedAt: "2026-02-15",
    uploadedBy: "Unnati Bamania",
    priority: "medium",
    tags: ["backend"],
    rating: 4,
  },
  {
    id: 6,
    status: "Draft",
    name: "Zeta",
    age: 42,
    active: false,
    featured: true,
    updatedAt: "2026-02-14",
    uploadedBy: "Kavya Menon",
    priority: "low",
    tags: ["ops", "api"],
    rating: 3,
  },
  {
    id: 7,
    status: "Ready",
    name: "Eta",
    age: 36,
    active: true,
    featured: false,
    updatedAt: "2026-02-13",
    uploadedBy: "Nitin Ranganath",
    priority: "high",
    tags: ["frontend", "backend"],
    rating: 5,
  },
  {
    id: 8,
    status: "In Review",
    name: "Theta",
    age: 30,
    active: false,
    featured: false,
    updatedAt: "2026-02-12",
    uploadedBy: "Arjun Patel",
    priority: "medium",
    tags: ["api"],
    rating: 2,
  },
  {
    id: 9,
    status: "Draft",
    name: "Iota",
    age: 24,
    active: true,
    featured: true,
    updatedAt: "2026-02-11",
    uploadedBy: "Unnati Bamania",
    priority: "low",
    tags: ["frontend"],
    rating: 3,
  },
  {
    id: 10,
    status: "Ready",
    name: "Kappa",
    age: 39,
    active: true,
    featured: false,
    updatedAt: "2026-02-10",
    uploadedBy: "Kavya Menon",
    priority: "high",
    tags: ["ops"],
    rating: 4,
  },
  {
    id: 11,
    status: "In Review",
    name: "Lambda",
    age: 28,
    active: false,
    featured: false,
    updatedAt: "2026-02-09",
    uploadedBy: "Arjun Patel",
    priority: "medium",
    tags: ["backend", "api"],
    rating: 1,
  },
  {
    id: 12,
    status: "Draft",
    name: "Mu",
    age: 33,
    active: true,
    featured: false,
    updatedAt: "2026-02-08",
    uploadedBy: "Nitin Ranganath",
    priority: "low",
    tags: ["frontend", "ops"],
    rating: 2,
  },
  {
    id: 13,
    status: "Ready",
    name: "Nu",
    age: 41,
    active: false,
    featured: true,
    updatedAt: "2026-02-07",
    uploadedBy: "Unnati Bamania",
    priority: "high",
    tags: ["backend"],
    rating: 5,
  },
  {
    id: 14,
    status: "In Review",
    name: "Xi",
    age: 26,
    active: true,
    featured: false,
    updatedAt: "2026-02-06",
    uploadedBy: "Kavya Menon",
    priority: "medium",
    tags: ["api", "frontend"],
    rating: 4,
  },
  {
    id: 15,
    status: "Draft",
    name: "Omicron",
    age: 37,
    active: false,
    featured: false,
    updatedAt: "2026-02-05",
    uploadedBy: "Arjun Patel",
    priority: "low",
    tags: ["ops"],
    rating: 3,
  },
  {
    id: 16,
    status: "Ready",
    name: "Pi",
    age: 32,
    active: true,
    featured: true,
    updatedAt: "2026-02-04",
    uploadedBy: "Nitin Ranganath",
    priority: "high",
    tags: ["backend", "ops"],
    rating: 4,
  },
  {
    id: 17,
    status: "In Review",
    name: "Rho",
    age: 29,
    active: false,
    featured: false,
    updatedAt: "2026-02-03",
    uploadedBy: "Unnati Bamania",
    priority: "medium",
    tags: ["frontend"],
    rating: 2,
  },
  {
    id: 18,
    status: "Draft",
    name: "Sigma",
    age: 45,
    active: true,
    featured: false,
    updatedAt: "2026-02-02",
    uploadedBy: "Kavya Menon",
    priority: "low",
    tags: ["api"],
    rating: 1,
  },
  {
    id: 19,
    status: "Ready",
    name: "Tau",
    age: 27,
    active: false,
    featured: true,
    updatedAt: "2026-02-01",
    uploadedBy: "Arjun Patel",
    priority: "high",
    tags: ["frontend", "backend"],
    rating: 5,
  },
  {
    id: 20,
    status: "In Review",
    name: "Upsilon",
    age: 35,
    active: true,
    featured: false,
    updatedAt: "2026-01-31",
    uploadedBy: "Nitin Ranganath",
    priority: "medium",
    tags: ["ops", "api"],
    rating: 3,
  },
  {
    id: 21,
    status: "Draft",
    name: "Phi",
    age: 38,
    active: false,
    featured: false,
    updatedAt: "2026-01-30",
    uploadedBy: "Unnati Bamania",
    priority: "low",
    tags: ["backend"],
    rating: 2,
  },
  {
    id: 22,
    status: "Ready",
    name: "Chi",
    age: 23,
    active: true,
    featured: false,
    updatedAt: "2026-01-29",
    uploadedBy: "Kavya Menon",
    priority: "high",
    tags: ["frontend"],
    rating: 4,
  },
  {
    id: 23,
    status: "In Review",
    name: "Psi",
    age: 34,
    active: false,
    featured: true,
    updatedAt: "2026-01-28",
    uploadedBy: "Arjun Patel",
    priority: "medium",
    tags: ["api", "ops"],
    rating: 3,
  },
  {
    id: 24,
    status: "Draft",
    name: "Omega",
    age: 40,
    active: true,
    featured: false,
    updatedAt: "2026-01-27",
    uploadedBy: "Nitin Ranganath",
    priority: "low",
    tags: ["backend", "frontend"],
    rating: 5,
  },
  {
    id: 25,
    status: "Ready",
    name: "Atlas",
    age: 31,
    active: true,
    featured: true,
    updatedAt: "2026-01-26",
    uploadedBy: "Unnati Bamania",
    priority: "high",
    tags: ["ops"],
    rating: 4,
  },
  {
    id: 26,
    status: "In Review",
    name: "Nova",
    age: 29,
    active: false,
    featured: false,
    updatedAt: "2026-01-25",
    uploadedBy: "Kavya Menon",
    priority: "medium",
    tags: ["api", "backend"],
    rating: 2,
  },
  {
    id: 27,
    status: "Draft",
    name: "Orion",
    age: 44,
    active: true,
    featured: false,
    updatedAt: "2026-01-24",
    uploadedBy: "Arjun Patel",
    priority: "low",
    tags: ["frontend", "ops"],
    rating: 3,
  },
  {
    id: 28,
    status: "Ready",
    name: "Zenith",
    age: 33,
    active: false,
    featured: true,
    updatedAt: "2026-01-23",
    uploadedBy: "Nitin Ranganath",
    priority: "high",
    tags: ["backend", "api"],
    rating: 5,
  },
];
